# Generated by Django 3.0.4 on 2020-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('MPI', 'MPI'), ('DE', 'DE')], default='MPI', max_length=5),
        ),
    ]
